name: Artifacts build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'artifacts/**'
      - '.github/workflows/artifacts-*.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  formatting-linting:
    uses: ./.github/workflows/formatting-linting.yml
  tests:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: artifacts
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'
          node-version: 18

      - name: 'Install the dependencies'
        run: 'yarn install --frozen-lockfile --ignore-scripts'

      - name: 'Build the artifacts'
        run: 'yarn build'
