name: SDK Publish

on:
  push:
    tags:
      - '*-configs'

jobs:
  check_tag:
    uses: ./.github/workflows/reusable-check-tag.yml
    with:
      ref: ${{ github.ref }}

  publish:
    needs: [check_tag]
    uses: ./.github/workflows/reusable-publish.yml
    with:
      package: ${{ needs.check_tag.outputs.package }}
      version: ${{ needs.check_tag.outputs.version }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
