name: 'js-client'

on:
  workflow_dispatch:
  push:
    paths:
      - 'js-client/**'
      - '.github/workflows/js-client-*.yml'

jobs:
  formatting-linting:
    uses: ./.github/workflows/formatting-linting.yml
  tests:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: js-client
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'
          node-version: 18

      - name: 'Install the dependencies'
        run: 'yarn install'

      - name: 'Build the js-client'
        run: 'yarn build'

      - name: 'Test the js-client'
        run: 'yarn test >> $GITHUB_STEP_SUMMARY'
