name: Pull Request Labeler
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - uses: actions/labeler@v5
        with:
          sync-labels: true
