name: SDK Publish

on:
  push:
    tags:
      - '*-sdk'

jobs:
  check_tag:
    uses: ./.github/workflows/reusable-check-tag.yml
    with:
      ref: ${{ github.ref }}

  tests:
    needs: [check_tag]
    if: ${{ needs.check_tag.outputs.package == 'sdk' }}
    uses: ./.github/workflows/sdk-tests.yml
    secrets:
      PUB_PINATA_JWT: ${{ secrets.PUB_PINATA_JWT }}

  publish:
    needs: [check_tag, tests]
    uses: ./.github/workflows/reusable-publish.yml
    with:
      package: ${{ needs.check_tag.outputs.package }}
      version: ${{ needs.check_tag.outputs.version }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
