name: SDK Tests

on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  formatting-linting:
    uses: ./.github/workflows/formatting-linting.yml
  tests:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: sdk
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'
          node-version: 18

      - name: 'Install the dependencies'
        run: 'yarn install --frozen-lockfile'

      - name: 'Build the sdk'
        run: 'yarn build'

      - name: 'Test the sdk'
        run: 'yarn test >> $GITHUB_STEP_SUMMARY'
