name: Subgraph Publish

on:
  push:
    tags:
      - '*-subgraph'

jobs:
  check_tag:
    uses: ./.github/workflows/reusable-check-tag.yml
    with:
      ref: ${{ github.ref }}

  tests:
    needs: [check_tag]
    if: ${{ needs.check_tag.outputs.package == 'subgraph' }}
    uses: ./.github/workflows/subgraph-tests.yml

  publish:
    needs: [check_tag, tests]
    uses: ./.github/workflows/reusable-publish.yml
    with:
      package: ${{ needs.check_tag.outputs.package }}
      version: ${{ needs.check_tag.outputs.version }}

    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
